// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcHJtjR05JoqTM47YN1KWCffnAdXGNOLw',
    appId: '1:907429473506:web:c7e490578e88d4fdb1c2bb',
    messagingSenderId: '907429473506',
    projectId: 'chatapp-eebdd',
    authDomain: 'chatapp-eebdd.firebaseapp.com',
    storageBucket: 'chatapp-eebdd.appspot.com',
    measurementId: 'G-FM14QMXZ9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0nU6htdug2IWcTklbT3MRV6HBuwU6H78',
    appId: '1:907429473506:android:87c443e7a06b494cb1c2bb',
    messagingSenderId: '907429473506',
    projectId: 'chatapp-eebdd',
    storageBucket: 'chatapp-eebdd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAExctA9tWM-lC6pxCP9sn9KZxAuUh3x_k',
    appId: '1:907429473506:ios:98d835b2fb2904d9b1c2bb',
    messagingSenderId: '907429473506',
    projectId: 'chatapp-eebdd',
    storageBucket: 'chatapp-eebdd.appspot.com',
    androidClientId: '907429473506-k19ecp58mb60anennoplbi5olorq4m7f.apps.googleusercontent.com',
    iosClientId: '907429473506-5tmvpdvlf50j7mus3ls0hj15tphi2c0q.apps.googleusercontent.com',
    iosBundleId: 'com.jaehee.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAExctA9tWM-lC6pxCP9sn9KZxAuUh3x_k',
    appId: '1:907429473506:ios:470c59806159b47cb1c2bb',
    messagingSenderId: '907429473506',
    projectId: 'chatapp-eebdd',
    storageBucket: 'chatapp-eebdd.appspot.com',
    androidClientId: '907429473506-k19ecp58mb60anennoplbi5olorq4m7f.apps.googleusercontent.com',
    iosClientId: '907429473506-tienvgbpfipk3tq5pj8ofk86c145862u.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
